# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from pathlib import Path
from webdriver_manager.chrome import ChromeDriverManager
from datetime import date
class TestTestupdate():
  def waitForElementVisible(self,locator,timeout=5):
    WebDriverWait(self.driver,timeout).until(expected_conditions.visibility_of_element_located(locator))
  def setup_method(self, method):
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
    self.driver.get("https://www.saucedemo.com/")
    self.driver.maximize_window()
    self.folderPath = str(date.today())
    Path(self.folderPath).mkdir(exist_ok=True)
    self.vars = {}
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testupdate(self):
    self.waitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"username\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
    self.waitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"password\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
    self.waitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"login-button\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
    self.waitForElementVisible((By.ID, "react-burger-menu-btn"))
    self.driver.find_element(By.ID, "react-burger-menu-btn").click()
    self.waitForElementVisible((By.ID, "about_sidebar_link"))
    self.waitForElementVisible((By.ID, "logout_sidebar_link"))
    self.driver.find_element(By.ID, "logout_sidebar_link").click()
  
  def test_login_around(self):
    self.waitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"username\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
    self.waitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"password\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
    self.waitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"login-button\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
    self.waitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-onesie\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-onesie\"]").click()
    self.waitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-backpack\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-backpack\"]").click()
    self.waitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]").click()
    self.waitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-onesie\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-onesie\"]").click()
    self.waitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-backpack\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-backpack\"]").click()
    self.driver.find_element(By.CLASS_NAME, "shopping_cart_link").click()
    self.waitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-bolt-t-shirt\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-bolt-t-shirt\"]").click()
    self.waitForElementVisible((By.CLASS_NAME, "btn_secondary"))
    self.driver.find_element(By.CLASS_NAME, "btn_secondary").click()
    self.waitForElementVisible((By.ID, "react-burger-menu-btn"))
    self.driver.find_element(By.ID, "react-burger-menu-btn").click()
    self.waitForElementVisible((By.ID, "about_sidebar_link"))
    self.driver.find_element(By.ID, "about_sidebar_link").click()
  
